### ISSUE TITLE
No module named 'PanPA._main'

### ISSUE THREAD

**Issue by zhengluo-zz** [fawaz-dabbaghieh/PanPA#2]
When I run PanPA, I encounter the following issue
```
Traceback (most recent call last):
  File "/share/home/zluo24/SOFTWARE/aarch64/anaconda3/bin/PanPA", line 5, in <module>
    from PanPA.main import main
  File "/share/home/zluo24/.local/lib/python3.12/site-packages/PanPA/main.py", line 6, in <module>
    from PanPA._main import _main
ModuleNotFoundError: No module named 'PanPA._main'
```
How can I resolve it?

**Comment by fawaz-dabbaghieh** [comment]
Hi,

Could you give more details.
- How did you install it?
- What version of Python, Cython, and setuptools are you using?
- What system are you using?
- What did you run to get this error.

Best,
Fawaz

**Comment by zhengluo-zz** [comment]
I use this command to install. `python setup.py install`
The versions of Python and Cython I am using are `Python 3.12.7` and `Cython version 0.29.21`
I am using a Linux system.
When I run PanPA, it gives the above error.

**Comment by fawaz-dabbaghieh** [comment]
Could you let me know which version of Setuptools?

**Comment by zhengluo-zz** [comment]
75.1.0

**Comment by fawaz-dabbaghieh** [comment]
OK, I just pushed small changes, there was something commented out in the setup file. Also, it seems to have problems with newer python version, so unfortunately for now you need to limit the Python version between 3.6 and 3.8. 

I recommend to make a new conda environment using the `environment.yml` file provided, or just start a new environment with a python version in that range, simply install the required cython and setuptools version and then run `python3 setup.py install` and it should work. I just tried this now on a fresh conda environment and it worked for me.

I need to spend some time later to figure out the bugs related to the newer Python versions.

**Comment by zhengluo-zz** [comment]
I reinstalled it following the steps below.
```
conda env create -f environment.yml
conda activate panpa
python3 setup.py install
```
But the following error still occurred.
```
Traceback (most recent call last):
  File "/share/home/zluo24/SOFTWARE/aarch64/anaconda3/envs/panpa/bin/PanPA", line 33, in <module>
    sys.exit(load_entry_point('PanPA==2.1.2', 'console_scripts', 'PanPA')())
  File "/share/home/zluo24/SOFTWARE/aarch64/anaconda3/envs/panpa/bin/PanPA", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/share/home/zluo24/SOFTWARE/aarch64/anaconda3/envs/panpa/lib/python3.8/importlib/metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "/share/home/zluo24/SOFTWARE/aarch64/anaconda3/envs/panpa/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/share/home/zluo24/SOFTWARE/aarch64/PanPA/PanPA/main.py", line 6, in <module>
    from PanPA._main import _main
ModuleNotFoundError: No module named 'PanPA._main'
```
The software versions in the new environment are as follows:
```
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-aarch64 2.43                 h4c662bb_2    conda-forge
ca-certificates           2025.1.31            hcefe29a_0    conda-forge
cython                    0.29.21          py38h0119ad3_2    conda-forge
kernel-headers_linux-aarch64 4.18.0              h05a177a_18    conda-forge
ld_impl_linux-aarch64     2.43                 h80caac9_2    conda-forge
libffi                    3.2.1             h4c5d2ac_1007    conda-forge
libgcc                    14.2.0               he277a41_1    conda-forge
libgcc-ng                 14.2.0               he9431aa_1    conda-forge
libgomp                   14.2.0               he277a41_1    conda-forge
liblzma                   5.6.3                h86ecc28_1    conda-forge
liblzma-devel             5.6.3                h86ecc28_1    conda-forge
libsqlite                 3.46.0               hf51ef55_0    conda-forge
libstdcxx                 14.2.0               h3f4de04_1    conda-forge
libstdcxx-ng              14.2.0               hf1166c9_1    conda-forge
libzlib                   1.2.13               h68df207_6    conda-forge
ncurses                   6.5                  ha32ae93_3    conda-forge
openssl                   1.1.1w               h31becfc_0    conda-forge
panpa                     2.1.2                    pypi_0    pypi
pip                       24.3.1             pyh8b19718_0    conda-forge
python                    3.8.0                heaf0f07_5    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.2                  h8fc344f_1    conda-forge
setuptools                75.1.0                   pypi_0    pypi
sqlite                    3.46.0               hdc7ab3c_0    conda-forge
sysroot_linux-aarch64     2.17                h68829e0_18    conda-forge
tk                        8.6.13               h194ca79_0    conda-forge
tzdata                    2025a                h78e105d_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
xz                        5.6.3                h2dbfc1b_1    conda-forge
xz-gpl-tools              5.6.3                h2dbfc1b_1    conda-forge
xz-tools                  5.6.3                h86ecc28_1    conda-forge
zlib                      1.2.13               h68df207_6    conda-forge
```

**Comment by fawaz-dabbaghieh** [comment]
Did you pull the repo again after I pushed the new changes?

Could you show me the log after running `python3 setup.py install`
Because I just tried the same you showed and it worked for me.

**Comment by zhengluo-zz** [comment]
Yes, I pulled again.
Below is the log.
[log.txt](https://github.com/user-attachments/files/18632832/log.txt)

**Comment by fawaz-dabbaghieh** [comment]
Weird! It seem to have been installed successfully, if you look at the end. So I am not sure why you're still getting that error.

Can you try to run the binary `/share/home/zluo24/SOFTWARE/aarch64/anaconda3/envs/panpa/bin/./PanPA`, because when you are just runnig `PanPA` it might still be using the old broken binary

**Comment by zhengluo-zz** [comment]
Thank you for patiently helping me identify the issue. I was previously using the ARM architecture, which didn't run successfully, but when I switched to X86, the issue was resolved.
This is likely due to compatibility differences between the two architectures.

**Comment by fawaz-dabbaghieh** [comment]
Oh, I didn't notice! Glad it worked! And thanks for spotting the bugs, I should work on this a bit more to make it easier for the users to install/use.

Please don't hesitate to open new issues while using, or if you have any questions about usage.

Best!
